### ISSUE TITLE
Add d11 and u22

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/unibuild#20]
Debian 11 and Ubuntu 22 have problems building (same problem, having to do with a patch).

Should also look into getting rid of compatibility level 9, which gets warned about.

**Comment by tonin** [comment]
A first set of images are ready: [D11](https://github.com/perfsonar/unibuild/pkgs/container/unibuild%2Fd11) and [U22](https://github.com/perfsonar/unibuild/pkgs/container/unibuild%2Fu22)

**Comment by laeti-tia** [comment]
These images seem to be working fine, can be closed.
