### ISSUE TITLE
Adding support for multi-architecture images/packages

### ISSUE THREAD

**Issue by tonin** [perfsonar/unibuild#23]
Given that we provide multi-architecture packages for perfSONAR, it would be helpful to provide multi-architecture Docker images of Unibuild.

**Comment by mfeit-internet2** [comment]
Should be able to do this by adding this to the [`with` section](https://github.com/perfsonar/unibuild/blob/54ba0a3ab2952feb89e269a5a57e309e2c486ea9/.github/workflows/docker-publish.yml#L75) of the publisher YML:

```
platforms: linux/amd64,linux/arm64,linux/arm/v7
```
