### ISSUE TITLE
Shouldn't `unibuild clean` be the same as `make clean` at top level dir?

### ISSUE THREAD

**Issue by tonin** [perfsonar/unibuild#27]
`unibuild clean` only clears the `${UNIBUILD_REPO_DIR}` directory, but leaves alone anything in `*/unibuild-work/products/` so that a subsequent `unbuild gather` will try to collect multiple packages accumulating in `*/unibuild-work/products/`

I think those should be removed as well ... and maybe the other tasks listed in the top-level Makefile clean target.

**Comment by mfeit-internet2** [comment]
It should and now it does.
